# name: Build
# on: [push, pull_request]
# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2
#     - name: Build
#       uses: docker/build-push-action@v3
#       with:
#         push: false

  name: docker-build
  on:
    push:
      branches:
        - 'master'
      tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'

  jobs:
    build:
      runs-on: ubuntu-latest
      env:
        IMG_NAME: ${{ variables.IMG_NAME }}

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        
        -
          name: Docker metadata
          id: metadata
          uses: docker/metadata-action@v3
          with:
            images: ${{ env.IMG_NAME }}
            tags: |
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
        -
          name: Login to Jfrog artifactory
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.JFROG_URL }}
            username: ${{ secrets.JFROG_USERNAME }}
            password: ${{ secrets.JFROG_PASSWORD }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        # -
        #   name: Build and push
        #   uses: docker/build-push-action@v2
        #   with:
        #     context: .
        #     file: ./Dockerfile
        #     push: true
        #     tags: ${{ secrets.JFROG_URL }}/$IMG_NAME:latest
        -
          name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.')}}
            tags: ${{ steps.metadata.outputs.tags }}
            labels: ${{ steps.metadata.outputs.labels }}

