---
  name: docker-build
  on:
    push:
      branches:
        - 'main'

  jobs:
    build:
      runs-on: ubuntu-latest
      env:
       IMG_NAME: ${{ variables.IMG_NAME }}

      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Jfrog artifactory
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.JFROG_URL }}
            username: ${{ secrets.JFROG_USERNAME }}
            password: ${{ secrets.JFROG_PASSWORD }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags:  ${{ secrets.JFROG_URL }}/$IMG_NAME:${{ secrets.MAJOR }}-${{ github.sha }}
